IPL MATHCES DATA CLEANING PRACTICE

IMPORTING NECESSARIES LIBARIES AND DATAFRAME

In [1]:
import pandas as pd
df = pd.read_csv('ipl-matches.csv')
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [2]:
df['Season'].isnull().sum()

0

OBSERVING THE COLUMNS

In [3]:
df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

RENAMING SOME COLUMNS FOR BETTER UNDERSTANDING

In [4]:
df = df.rename(columns={
    'MatchNumber' : 'Match Number',
    'Team1' : 'Team 1',
    'Team2' : 'Team 2',
    'TossWinner' : 'Toss Winner',
    'TossDecision' : 'Toss Decision',
    'SuperOver' : 'Super Over',
    'WinningTeam' : 'Winning Team',
    'WonBy' : 'Won By',
    'method' : 'Method',
    'Player_of_Match' : 'Player of Match',
    'Team1Players' : 'Team 1 Players',
    'Team2Players' : 'Team 2 Players',
    'Umpire1' : 'Umpire 1',
    'Umpire2' : 'Umpire 2'
})
df.head(2)

,ID,City,Date,Season,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,Super Over,Winning Team,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

CHECKING NULL VALUES COLUMNS

In [5]:
df.isnull().any()

ID                 False
City                True
Date               False
Season             False
Match Number       False
Team 1             False
Team 2             False
Venue              False
Toss Winner        False
Toss Decision      False
Super Over          True
Winning Team        True
Won By             False
Margin              True
Method              True
Player of Match     True
Team 1 Players     False
Team 2 Players     False
Umpire 1           False
Umpire 2           False
dtype: bool

AFTER CLOSELY OBSERVATION THIS 4 ROWS [205,437,464,708] HAS MISSING VALUES. IF WE DROP THIS 4 ROWS MISSING VALUES COPLEXITY DECRESES DRAMATICALLY

DROPING [205,437,464,708] ROWS

In [6]:
df= df.drop([205,437,464,708])

CHECKING MISSING VALUES AGAIN

In [7]:
df.isnull().any()

ID                 False
City                True
Date               False
Season             False
Match Number       False
Team 1             False
Team 2             False
Venue              False
Toss Winner        False
Toss Decision      False
Super Over         False
Winning Team       False
Won By             False
Margin              True
Method              True
Player of Match    False
Team 1 Players     False
Team 2 Players     False
Umpire 1           False
Umpire 2           False
dtype: bool

NOW WE HAVE ONLY THREE COLUMNS (City, Margin AND Method) HAS MISSING VALUES

CHECKING WHOSE ROWS OF City COLUMN'S HAS MISSING VALUES

In [8]:
df[df['City'].isna()==1].head(2)
# df['City'].isnull().sum()

,ID,City,Date,Season,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,Super Over,Winning Team,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
137,1237177,NaN,2020-11-05,2020/21,Qualifier 1,Mumbai Indians,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Mumbai Indians,Runs,57.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,Nitin Menon

SPLITING VENUES FIRST STRING TO FILL THE MISSIGN VALUES OF CITY COLUMN

In [9]:
a=df['Venue'].str.split(pat=' ').str[0]
a

0      Narendra
1      Narendra
2          Eden
3          Eden
4      Wankhede
         ...
945        Eden
946    Wankhede
947       Feroz
948      Punjab
949           M
Name: Venue, Length: 946, dtype: object

FILLING CITY COLUMNS MISSING VALUES BY VENUE COLUMNS FIRST STRING

In [10]:
df['City'] = df['City'].fillna(a)

CHECKING THE CITY COLUMN MISSING VALUES IS EXISTED OR NOT

In [11]:
df['City'].isna().sum()

0

CHECKING MARGIN COLUMNS DATATYPES TO FILL THE MISSING VALUES

In [12]:
df['Margin'].dtypes

dtype('float64')

FILLING MARGIN COLUMNS MISSING VALUES BY 0.0 AS IT IS A FLOAT DATATYPE COLUMNS

In [13]:
df['Margin'] = df['Margin'].fillna('0.0')

CHECKING MARGIN COLUMNS MISSING VALUES EXISTED OR NOT

In [14]:
df['Margin'].isnull().sum()

0

CHECKING METHOD COLUMNS DATATYPES

In [15]:
df.dtypes

ID                  int64
City               object
Date               object
Season             object
Match Number       object
Team 1             object
Team 2             object
Venue              object
Toss Winner        object
Toss Decision      object
Super Over         object
Winning Team       object
Won By             object
Margin             object
Method             object
Player of Match    object
Team 1 Players     object
Team 2 Players     object
Umpire 1           object
Umpire 2           object
dtype: object

CHECKING METHOD COLUMNS MISSING VALUES ROWS

In [16]:
df[df['Method'].isna()==1].head(2)

,ID,City,Date,Season,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,Super Over,Winning Team,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

FILLING METHOD COLUMNS MISSING VALUES BY NA AS THIS COLUMNS ONLY EXIST NA AND D\L. VALUES NA WILL NOT EFFECT THE COLUMNS DATA

In [17]:
df['Method'] = df['Method'].fillna('NA')

CHECKING THE METHOD COLUMNS MISSIG VALUES IS EXISTED OR NOT

In [18]:
df['Method'].isna().sum()

0

FINAL CHECKING OF ALL THE COLUMNS HAS MISSING VALUES OR NOT

In [19]:
df.isnull().any()

ID                 False
City               False
Date               False
Season             False
Match Number       False
Team 1             False
Team 2             False
Venue              False
Toss Winner        False
Toss Decision      False
Super Over         False
Winning Team       False
Won By             False
Margin             False
Method             False
Player of Match    False
Team 1 Players     False
Team 2 Players     False
Umpire 1           False
Umpire 2           False
dtype: bool

MISSING VALUES HANDLING IS DONE

=======================================

CONVERTING DATE COLUMN TO DATETIME DATATYPE AND CREATING MONTH AND DAY COLUMNS

In [20]:
df.dtypes

ID                  int64
City               object
Date               object
Season             object
Match Number       object
Team 1             object
Team 2             object
Venue              object
Toss Winner        object
Toss Decision      object
Super Over         object
Winning Team       object
Won By             object
Margin             object
Method             object
Player of Match    object
Team 1 Players     object
Team 2 Players     object
Umpire 1           object
Umpire 2           object
dtype: object

CONVERTING DATE COLUMNS TO DATETIME DATATYPES

In [21]:
df['Date'] = pd.to_datetime(df['Date'])

In [22]:
df['Date']

0     2022-05-29
1     2022-05-27
2     2022-05-25
3     2022-05-24
4     2022-05-22
         ...
945   2008-04-20
946   2008-04-20
947   2008-04-19
948   2008-04-19
949   2008-04-18
Name: Date, Length: 946, dtype: datetime64[ns]

CREATING MONTH AND DAY COLUMNS

In [23]:
df['Month']=df['Date'].dt.month_name()

In [24]:
df['Day'] = df['Date'].dt.day_name()

In [25]:
df.columns

Index(['ID', 'City', 'Date', 'Season', 'Match Number', 'Team 1', 'Team 2',
       'Venue', 'Toss Winner', 'Toss Decision', 'Super Over', 'Winning Team',
       'Won By', 'Margin', 'Method', 'Player of Match', 'Team 1 Players',
       'Team 2 Players', 'Umpire 1', 'Umpire 2', 'Month', 'Day'],
      dtype='object')

In [26]:
df = df.drop(['ID','Date'], axis=1)

In [27]:
df.head()

,City,Season,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,Super Over,Winning Team,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2,Month,Day
0,Ahmedabad,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NA,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,May,Sunday
1,Ahmedabad,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NA,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,May,Friday
2,Kolkata,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NA,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,May,Wednesday
3,Kolkata,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NA,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,May,Tuesday
4,Mumbai,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NA,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,May,Sunday

In [28]:
df.columns

Index(['City', 'Season', 'Match Number', 'Team 1', 'Team 2', 'Venue',
       'Toss Winner', 'Toss Decision', 'Super Over', 'Winning Team', 'Won By',
       'Margin', 'Method', 'Player of Match', 'Team 1 Players',
       'Team 2 Players', 'Umpire 1', 'Umpire 2', 'Month', 'Day'],
      dtype='object')

RE=ORDERING MONTH AND DAY COLUMNS

In [29]:
col = df.pop('Month')
df.insert(2, col.name, col)

In [30]:
col = df.pop('Day')
df.insert(3, col.name, col)

In [31]:
df.head(2)

,City,Season,Month,Day,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,Super Over,Winning Team,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2
0,Ahmedabad,2022,May,Sunday,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NA,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,Ahmedabad,2022,May,Friday,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NA,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

CHECKING THE DATATYPE OF THE DATAFRAME AND MAKE NECESSARIES CHANGES IF NEEDED

In [32]:
df.dtypes

City               object
Season             object
Month              object
Day                object
Match Number       object
Team 1             object
Team 2             object
Venue              object
Toss Winner        object
Toss Decision      object
Super Over         object
Winning Team       object
Won By             object
Margin             object
Method             object
Player of Match    object
Team 1 Players     object
Team 2 Players     object
Umpire 1           object
Umpire 2           object
dtype: object

CHANGING DATATYPES OF MARGIN COLUMN

In [33]:
df['Margin'] = df['Margin'].astype(float)

In [34]:
df.dtypes

City                object
Season              object
Month               object
Day                 object
Match Number        object
Team 1              object
Team 2              object
Venue               object
Toss Winner         object
Toss Decision       object
Super Over          object
Winning Team        object
Won By              object
Margin             float64
Method              object
Player of Match     object
Team 1 Players      object
Team 2 Players      object
Umpire 1            object
Umpire 2            object
dtype: object

SEASON COLUMN DATATYPE IS IN OBJECT FORM WHEN I TRY TO CONVERT IT TO A NUMERIC TYPE DATA TYPE IT IS CONVERTED AS FLOAT. THIS IS HAPPENING BECAUSE THIS COLUMN CONTAIS 2008 AND 2028/09 TYPE DATA

FOR OVERCOME THIS PROBLEM WE HAVE TO MAKE TO COLUMNS LIKE SEASON START COLUMN AND SEASON END COLUMN

CREATING SEASON START COLUMN

In [35]:
df['Season Start'] = df['Season'].apply(lambda x: x.split('/')[0] if '/' in x else x)

CREATING SEASON END COLUMN

In [36]:
df['Season End'] = df['Season'].apply(lambda x: x.split('/')[1] if '/' in x else x)

FILLING 08 TYPE OF DATA AS 2008 IN SEASON END COLUMN

In [37]:
# Fix Season End to full year if only 2 digits (like '08' -> '2008')
df['Season End'] = df['Season End'].apply(
    lambda x: '20' + x if len(x) == 2 else x
)

In [38]:
df.head(2)

,City,Season,Month,Day,Match Number,Team 1,Team 2,Venue,Toss Winner,Toss Decision,...,Won By,Margin,Method,Player of Match,Team 1 Players,Team 2 Players,Umpire 1,Umpire 2,Season Start,Season End
0,Ahmedabad,2022,May,Sunday,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Wickets,7.0,NA,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022,2022
1,Ahmedabad,2022,May,Friday,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Wickets,7.0,NA,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,2022,2022

POP AND RE-INSERT 'SEASON START' AT THE SECOND COLUMN (INDEX 1)

In [39]:
col = df.pop('Season Start')
df.insert(1, 'Season Start', col)

POP AND RE-INSERT 'SEASON END' AT THE SECOND COLUMN (INDEX 2)

In [40]:
col = df.pop('Season End')
df.insert(2, 'Season End', col)

In [41]:
df = df.drop('Season', axis=1)

In [42]:
df.columns

Index(['City', 'Season Start', 'Season End', 'Month', 'Day', 'Match Number',
       'Team 1', 'Team 2', 'Venue', 'Toss Winner', 'Toss Decision',
       'Super Over', 'Winning Team', 'Won By', 'Margin', 'Method',
       'Player of Match', 'Team 1 Players', 'Team 2 Players', 'Umpire 1',
       'Umpire 2'],
      dtype='object')

In [43]:
df.dtypes

City                object
Season Start        object
Season End          object
Month               object
Day                 object
Match Number        object
Team 1              object
Team 2              object
Venue               object
Toss Winner         object
Toss Decision       object
Super Over          object
Winning Team        object
Won By              object
Margin             float64
Method              object
Player of Match     object
Team 1 Players      object
Team 2 Players      object
Umpire 1            object
Umpire 2            object
dtype: object

CONVERTING THE DATATYPES OF THE SEASON START AND SEASON END COLUMNS

In [44]:
df['Season Start'] = df['Season Start'].astype(int)

In [45]:
df['Season End'] = df['Season End'].astype(int)

In [46]:
df.dtypes

City                object
Season Start         int32
Season End           int32
Month               object
Day                 object
Match Number        object
Team 1              object
Team 2              object
Venue               object
Toss Winner         object
Toss Decision       object
Super Over          object
Winning Team        object
Won By              object
Margin             float64
Method              object
Player of Match     object
Team 1 Players      object
Team 2 Players      object
Umpire 1            object
Umpire 2            object
dtype: object

In [47]:
df.to_csv('cleaned_ipl.csv', index= False)